services:
    wellery_app:
        build: .
        container_name: wellery_portfolio
        restart: unless-stopped
        ports:
            - "1400:1400"
        networks: [central_proxy_net]
networks:
    central_proxy_net: { external: true }
